"""Dimension API."""

from typing import Protocol, Self, runtime_checkable

__version__ = "0.0.1.dev0"
__all__ = ["Dimension"]

@runtime_checkable
class Dimension(Protocol):
    def __eq__(self, other: Self, /) -> bool: ...
    def __mul__(self, other: Self, /) -> Self: ...
    def __div__(self, other: Self, /) -> Self: ...
    def __pow__(self, other: int, /) -> Self: ...
